### ISSUE TITLE
Article recommendation

### ISSUE THREAD

**Issue by tsingyu42** [mayuxi987/ai-psychology#1]
**1**

[[2310.19619] Towards A Holistic Landscape of Situated Theory of Mind in Large Language Models](https://arxiv.org/abs/2310.19619)

From [Mars-tin/awesome-theory-of-mind: Machine Theory of Mind Reading List. Built upon EMNLP Findings 2023 Paper: Towards A Holistic Landscape of Situated Theory of Mind in Large Language Models](https://github.com/Mars-tin/awesome-theory-of-mind)

**2**

[[2307.07871] The SocialAI School: Insights from Developmental Psychology Towards Artificial Socio-Cultural Agents](https://arxiv.org/abs/2307.07871)

[SocialAI School](https://sites.google.com/view/socialai-school)

**Comment by mayuxi987** [comment]
Thanks for the recommendation!!
